name: CnCombo
channels:
  - https://conda.graylab.jhu.edu
  - bioconda
  - anaconda
  - schrodinger
  - https://USERNAME:PASSWORD@conda.graylab.jhu.edu
  - salilab
  - conda-forge
  - omnia
dependencies:
  - biopython
  - numpy
  - openssl
  - prody
  - pip
  - pymol
  - python>=3.9
  - pyrosetta
  - pip:
      - argparse
      - topoly
